version: "3"
services:
  nodeapi:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "8080:8080"

  pythonapi:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "5000:5000"
